server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devbdb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: nbikch
    password: tom0312!

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  # security
  security:
    user:
      name: user1
      password: 1234

    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: 148208030996-ckfnonbv5uippt5n105bffun4bmrpuhs.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 290270110033944  # ? ID
            client-secret: ece7981ebf6c8e4f16ba24a09dfdd0f2  # ? ??? ??
            scope:
              - email
              - public_profile

          naver:
            client-id: 3ctPVlHkLbqMr6VdseZe
            client-secret: zv0FItz6l3
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        # provider ??
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  # ?? ??? ??
  upload:
    path: upload

  # ??? ?? ???
  pagination:
    write_pages: 10  # ?? write_pages ?. ? [???] ? ??? ???? ????
    page_rows: 10   # ?? page_rows ?.  ? '???'? ??? ?? ??? ?????

  # OAuth2
  oauth2:

    password: 1234

    # Kakao ??? ?? ???
    kakao:
      client-id: 61335c5470325ba740656e9c18f658fc   # ? ?
      redirect-uri: http://localhost:8080/oauth2/kakao/callback  # Redirect URI
      token-uri: https://kauth.kakao.com/oauth/token   # access token ?? URI
      user-info-uri: https://kapi.kakao.com/v2/user/me   # ??? profile ?? URI





